export type VoiceModelKind = "stt" | "tts" | "framework";

export interface VoiceModelCatalogItem {
  id: string;
  kind: VoiceModelKind;
  name: string;
  role: string;
  status: "wired" | "candidate" | "future";
  license: string;
  footprint: string;
  strengths: string[];
  endpointHint: string;
  localPaths?: string[];
  notes: string;
}

export const VOICE_MODEL_CATALOG: VoiceModelCatalogItem[] = [
  {
    id: "faster-distil-whisper-large-v3",
    kind: "stt",
    name: "Faster Distil Whisper Large v3",
    role: "Default batch STT",
    status: "wired",
    license: "Open model stack",
    footprint: "Fast GPU/CPU batch transcription",
    strengths: ["Production-proven", "Good punctuation with prompting", "Already wired in UVB"],
    endpointHint: "http://127.0.0.1:8001/v1/audio/transcriptions",
    localPaths: ["Z:\\Models\\whisper"],
    notes: "Keep as UVB's reliable local baseline for voice notes, Telegram audio, and uploaded files.",
  },
  {
    id: "whisper-cpp-streaming",
    kind: "stt",
    name: "whisper.cpp Streaming Lane",
    role: "Low-overhead local STT fallback",
    status: "candidate",
    license: "MIT",
    footprint: "C/C++ GGML Whisper runtime",
    strengths: ["CPU/GPU portable", "Good fallback runtime", "Useful for streaming adapters"],
    endpointHint: "whisper.cpp sidecar TBD",
    localPaths: ["Z:\\Models\\whisper"],
    notes: "Keep as the compact fallback and streaming experiment lane; faster-whisper remains the default until a measured barge-in win appears.",
  },
  {
    id: "nvidia-parakeet-tdt-0.6b-v2",
    kind: "stt",
    name: "NVIDIA Parakeet TDT 0.6B v2",
    role: "Fast English STT candidate",
    status: "candidate",
    license: "CC-BY-4.0",
    footprint: "600M parameters",
    strengths: ["Very fast", "Punctuation/capitalization", "Timestamp prediction"],
    endpointHint: "NeMo/OpenAI-compatible sidecar TBD",
    notes: "Best next STT sidecar candidate for low-latency English transcription on local NVIDIA hardware.",
  },
  {
    id: "nvidia-canary-qwen-2.5b",
    kind: "stt",
    name: "NVIDIA Canary-Qwen 2.5B",
    role: "Accuracy/ASR-LLM candidate",
    status: "candidate",
    license: "Open model card",
    footprint: "2.5B parameters",
    strengths: ["Open ASR leaderboard strength", "ASR plus LLM-style speech understanding", "Long-form candidate"],
    endpointHint: "NeMo/OpenAI-compatible sidecar TBD",
    notes: "Candidate for high-accuracy long-form transcription and richer audio-language tasks.",
  },
  {
    id: "vibevoice-asr-7b",
    kind: "stt",
    name: "Microsoft VibeVoice ASR 7B",
    role: "Long-form diarized STT candidate",
    status: "candidate",
    license: "Microsoft research release",
    footprint: "7B long-context speech model",
    strengths: ["Up to 60-minute single-pass audio", "Speaker diarization", "Timestamps and hotwords"],
    endpointHint: "VibeVoice ASR sidecar / vLLM-ASR TBD",
    notes: "Best fit for podcasts, meetings, video narration, and long recordings where speaker continuity matters.",
  },
  {
    id: "kokoro-82m",
    kind: "tts",
    name: "Kokoro 82M",
    role: "Default fast local TTS",
    status: "wired",
    license: "Apache-2.0",
    footprint: "82M parameters",
    strengths: ["Very fast", "Cheap to run", "Already wired in UVB", "Good agent voice baseline"],
    endpointHint: "http://127.0.0.1:8880/v1/audio/speech",
    localPaths: ["Z:\\Models\\Kokoro-82M"],
    notes: "Keep as the default realtime Sophia voice path.",
  },
  {
    id: "chatterbox-turbo",
    kind: "tts",
    name: "Resemble Chatterbox Turbo",
    role: "Low-latency cloning candidate",
    status: "candidate",
    license: "MIT",
    footprint: "350M parameters",
    strengths: ["Zero-shot cloning", "Lower VRAM than original Chatterbox", "Paralinguistic tags"],
    endpointHint: "Chatterbox server / OpenAI-compatible wrapper TBD",
    notes: "Primary next TTS sidecar target for Sophia voice agents and expressive podcast seats.",
  },
  {
    id: "chatterbox-multilingual",
    kind: "tts",
    name: "Resemble Chatterbox Multilingual",
    role: "Multilingual clone candidate",
    status: "candidate",
    license: "MIT",
    footprint: "500M parameters",
    strengths: ["23 languages", "Zero-shot cloning", "Localization lane"],
    endpointHint: "Chatterbox server / multilingual model switch TBD",
    notes: "Keep alongside Turbo when multilingual podcast or localization workflows matter.",
  },
  {
    id: "vibevoice-realtime-0.5b",
    kind: "tts",
    name: "Microsoft VibeVoice Realtime 0.5B",
    role: "Realtime streaming TTS candidate",
    status: "candidate",
    license: "Microsoft research release",
    footprint: "0.5B parameters",
    strengths: ["Streaming text input", "Low first-audio latency", "Robust long-form output"],
    endpointHint: "VibeVoice realtime sidecar TBD",
    localPaths: ["Z:\\Models\\vibevoice\\VibeVoice-Realtime-0.5B", "Z:\\Models\\vibevoice\\VibeVoice-Realtime"],
    notes: "Best fit for live Sophia responses once a local FastAPI/OpenAI-compatible runner is attached.",
  },
  {
    id: "vibevoice-tts-1.5b",
    kind: "tts",
    name: "Microsoft VibeVoice TTS 1.5B",
    role: "Long-form podcast candidate",
    status: "candidate",
    license: "Microsoft research release",
    footprint: "1.5B parameters",
    strengths: ["Up to 90-minute synthesis", "Multi-speaker dialogue", "Podcast-first structure"],
    endpointHint: "VibeVoice long-form sidecar TBD",
    localPaths: ["Z:\\Models\\vibevoice\\VibeVoice-1.5B"],
    notes: "Primary podcast engine candidate for multi-seat scripts and long continuous narration.",
  },
  {
    id: "vibevoice-large-local",
    kind: "tts",
    name: "VibeVoice Large Local",
    role: "High-quality local podcast lane",
    status: "candidate",
    license: "Local model assets",
    footprint: "Large safetensors / Q8 / ONNX INT4 variants",
    strengths: ["Local large weights present", "Q8 and INT4 variants found", "Quality/performance benchmark lane"],
    endpointHint: "Local VibeVoice runner TBD",
    localPaths: [
      "Z:\\Models\\vibevoice\\VibeVoice-Large",
      "Z:\\Models\\vibevoice\\VibeVoice-Large-Q8",
      "Z:\\Models\\vibevoice\\vibevoice-onnx-int4",
      "Z:\\Models\\VibeVoice-Large",
    ],
    notes: "Use for a quality shootout after the realtime and 1.5B runners are stable.",
  },
  {
    id: "moss-tts-realtime",
    kind: "tts",
    name: "MOSS-TTS Realtime",
    role: "Realtime barge-in candidate",
    status: "candidate",
    license: "OpenMOSS research release",
    footprint: "1.7B realtime speech model",
    strengths: ["Low-latency voice agents", "Multi-turn voice consistency", "Streaming-friendly"],
    endpointHint: "MOSS realtime sidecar TBD",
    notes: "High-priority candidate for live Sophia once we benchmark it against Chatterbox Turbo and VibeVoice Realtime.",
  },
  {
    id: "moss-tts-nano",
    kind: "tts",
    name: "MOSS-TTS Nano",
    role: "CPU-friendly realtime fallback",
    status: "candidate",
    license: "OpenMOSS research release",
    footprint: "100M parameters / ONNX CPU path",
    strengths: ["CPU-capable", "Streaming inference", "Multilingual cloning"],
    endpointHint: "MOSS Nano HTTP/ONNX sidecar TBD",
    notes: "Useful as a lightweight local reader/fallback and a deployment sanity check when GPU TTS lanes are busy.",
  },
  {
    id: "moss-ttsd",
    kind: "tts",
    name: "MOSS-TTSD",
    role: "Long-form spoken dialogue candidate",
    status: "candidate",
    license: "OpenMOSS research release",
    footprint: "8B dialogue generation model",
    strengths: ["Long-form dialogue", "Multi-party speech", "Zero-shot references"],
    endpointHint: "MOSS dialogue sidecar TBD",
    notes: "Podcast shootout lane against VibeVoice for scripted multi-speaker episodes.",
  },
  {
    id: "fish-audio-s2-pro",
    kind: "tts",
    name: "Fish Audio S2 Pro",
    role: "Expressive streaming clone candidate",
    status: "candidate",
    license: "Open model/code release",
    footprint: "Large expressive TTS with SGLang inference",
    strengths: ["Natural-language emotion tags", "Streaming inference", "Multi-speaker and multi-turn generation"],
    endpointHint: "Fish Speech S2 sidecar TBD",
    notes: "Benchmark for emotional direction and cloning quality; heavier than Kokoro/Chatterbox but potentially excellent on the 5090-class box.",
  },
  {
    id: "f5-tts",
    kind: "tts",
    name: "F5-TTS / F5R-TTS",
    role: "Speaker similarity candidate",
    status: "candidate",
    license: "Open source",
    footprint: "Flow-matching TTS",
    strengths: ["Voice cloning", "Speaker similarity", "Research momentum"],
    endpointHint: "F5 sidecar / OpenAI-compatible wrapper TBD",
    notes: "Useful as a comparison backend for clone profile quality.",
  },
  {
    id: "xtts-v2",
    kind: "tts",
    name: "XTTS-v2",
    role: "Legacy clone baseline",
    status: "candidate",
    license: "Coqui/open-source lineage",
    footprint: "Established multilingual cloning stack",
    strengths: ["Known baseline", "Multilingual cloning", "Broad community examples"],
    endpointHint: "XTTS sidecar TBD",
    notes: "Keep as a benchmark/fallback, not a top rebuild target unless it wins local quality tests.",
  },
  {
    id: "cosyvoice2",
    kind: "tts",
    name: "CosyVoice2",
    role: "Multilingual streaming candidate",
    status: "candidate",
    license: "Open source",
    footprint: "LLM-style speech synthesis",
    strengths: ["Multilingual", "Streaming synthesis", "Voice cloning scripts available"],
    endpointHint: "CosyVoice2 sidecar / OpenAI-compatible wrapper TBD",
    localPaths: ["Z:\\Models\\TTS\\CosyVoice"],
    notes: "Candidate for multilingual Sophia and longer-form podcast generation.",
  },
  {
    id: "spark-glm-qwen-local",
    kind: "tts",
    name: "Spark / GLM / Qwen Local TTS Lane",
    role: "Local experimental voice lane",
    status: "candidate",
    license: "Varies by model",
    footprint: "Local model folders and LoRA assets",
    strengths: ["Local assets already present", "Clone experiments", "Good benchmark candidates"],
    endpointHint: "Custom sidecar TBD",
    localPaths: [
      "Z:\\Spark-TTS",
      "Z:\\Models\\GLM-TTS",
      "Z:\\Models\\loras\\qwen3_tts",
      "Z:\\Models\\loras\\chatterbox",
    ],
    notes: "This is where Quinn/Qwen-style local experiments should be registered once their runner contract is known.",
  },
  {
    id: "orpheus-dia-zonos",
    kind: "tts",
    name: "Orpheus / Dia / Zonos Lane",
    role: "Expressiveness research lane",
    status: "future",
    license: "Varies by model",
    footprint: "Higher GPU demand",
    strengths: ["Expressive long-form speech", "Dialogue and emotion experiments", "Quality ceiling"],
    endpointHint: "Research lane TBD",
    notes: "Keep as experimental options after Chatterbox Turbo, VibeVoice, F5, and CosyVoice2 adapters are stable.",
  },
  {
    id: "pipecat",
    kind: "framework",
    name: "Pipecat",
    role: "Primary realtime voice orchestration lane",
    status: "wired",
    license: "Open-source framework",
    footprint: "Python streaming voice pipeline",
    strengths: ["Streaming STT/LLM/TTS pipeline", "Barge-in architecture fit", "Subagents and Flows path"],
    endpointHint: "services/voice-agent/pipecat_agent.py",
    localPaths: ["services\\voice-agent\\pipecat_agent.py", ".venv-pipecat"],
    notes: "Keep investing here: it maps cleanly to Sophia brain/tool/memory subagents while preserving local STT/TTS provider swaps.",
  },
  {
    id: "livekit-agents",
    kind: "framework",
    name: "LiveKit Agents",
    role: "Realtime transport/framework watch lane",
    status: "candidate",
    license: "Open-source framework",
    footprint: "Realtime media + agents stack",
    strengths: ["WebRTC-native", "Production transport", "Agent framework ecosystem"],
    endpointHint: "Adapter TBD",
    notes: "Worth keeping on the radar, but no reason to displace the current Pipecat lane without a specific transport need.",
  },
  {
    id: "vocode",
    kind: "framework",
    name: "Vocode",
    role: "Legacy voice-agent framework watch lane",
    status: "future",
    license: "Open-source framework",
    footprint: "Voice-agent orchestration framework",
    strengths: ["Known ecosystem", "Provider abstraction", "Historical baseline"],
    endpointHint: "No adapter planned",
    notes: "Track lightly only; current signal favors Pipecat for UVB's local-first realtime architecture.",
  },
];
